version: '3.8'
services:
  db:
    image: postgres:15
    container_name: bookings-postgres
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata_bookings:/var/lib/postgresql/data

volumes:
  pgdata_bookings: